### ISSUE TITLE
Add Command: Difference between user guide and app

### ISSUE THREAD

**Issue by Bonzzz3** [AY2425S1-CS2103T-T10-1/tp#116]
### **Description**
Add Command: Difference between user guide and app

### **Details**
There might be a difference between user guide format for add command and the code behaviour.

![image](https://github.com/user-attachments/assets/9f73b013-bae4-4b3d-98ba-87c773abe44d)
_Section of add command in user guide_

![image](https://github.com/user-attachments/assets/605c8d6b-d5a0-4ba0-a417-78f04f6de667)
_output of `add n/John Doe p/98765432 e/johnd@example.c a/John street, block 123, #01-01 b/40 s/Male` (failed)_

![image](https://github.com/user-attachments/assets/12364131-8f95-4f87-b817-e9324bb5ff2f)
_output of `add n/John Doe p/98765432 e/johnd@example.co a/John street, block 123, #01-01 b/40 s/Male` (succeed)_

In the code, it seems that `.c` is treated as the domain name and not the whole `@example.c` which is not the same as stated in user guide and the error message provided.

Example given in user guide is `e/johnd@example.com` which has a `.` but in user guide it is stated that "The domain label should consist of alphanumeric characters separated only be hyphens, if any." , which contradicts each other.

**Comment by LynetteLeeSiYing** [comment]
From what I have understand from the user guide was:
 "example.com" is domain name,
"example" and "com" are domain labels 

so from your example given here, ".c" will throw an error as the whole domain must end with **domain label** with at least 2 characters

**Comment by Bonzzz3** [comment]
I see, I think it would be good to include examples like this in user guide in the future to avoid confusion to the users. Thanks!
