### ISSUE TITLE
Sort command: Behaviour when no appointment date is present

### ISSUE THREAD

**Issue by Bonzzz3** [AY2425S1-CS2103T-T10-1/tp#123]
### **Description**
When there is no appointment dates, list remains the same which may confuse users.
![image](https://github.com/user-attachments/assets/b8880743-7a31-483a-a6fa-268b570d91f2)
_output of `sort`_

### **Suggested Improvements**
Some of the improvements I can think of:
1. Update the **user guide** for the sort command to specify that contacts will be sorted by appointment dates, then any contacts without appointments will remain sorted alphabetically at the end of the list.
2. Display an **error message** when no contacts have appointment dates, such as `No contacts with appointment dates found.`
3. When there are no contacts with appointment dates, display only the error message (as in suggestion 2) and an **empty list** to indicate no results for sort.

**Comment by OttoTan** [comment]
I prefer 1 and 2, rather than returning an empty list, because the user will have to make an unnecessary additional command `list` just to get the list back
