### ISSUE TITLE
Sort/List Command: No way to reverse alphabetical sorting

### ISSUE THREAD

**Issue by myrilla12** [AY2425S1-CS2103T-T10-1/tp#132]
### Description
Upon executing the `sort` command, there is no way to reverse this sorting and return to alphabetical sorting (aside from exiting and reopening the application or executing other commands - BUT doesn't work for `list`). 

### Suggested improvement
- Maybe an `unsort` command to return to alphabetical sorting
- Or if `sort` is executed again while contacts are sorted by appointments it will sort alphabetically
- Or `sort` can take in arguments e.g. `sort appointments` will sort by appointment date and `sort alpha` will sort alphabetically
- Or `list` will automatically list in alphabetical order so user can execute `list` after `sort` if they wish to return to alphabetical sorting

**Comment by ritvi12** [comment]
I think for this we can add the command to list that when list is executed it returns to alphabetical order. Cause the alphabetical ordering is like the default ordering we are using for the list. Cause having sort then unsort doesn't really make sense.

**Comment by myrilla12** [comment]
> I think for this we can add the command to list that when list is executed it returns to alphabetical order. Cause the alphabetical ordering is like the default ordering we are using for the list. Cause having sort then unsort doesn't really make sense.

Agreed I think having list automatically list in alphabetical order would be the best solution!
