### ISSUE TITLE
Case sensitivite (Delete, Edit, Star, Unstar, View)

### ISSUE THREAD

**Issue by myrilla12** [AY2425S1-CS2103T-T10-1/tp#133]
### Description
`delete`, `edit`, `star`, `unstar` and `view` are case sensitive for the NAME parameter while `find` is not case sensitive. This is not reflected in the user guide and might prove a little inconsistent given that `find` is not case sensitive. 

![Screenshot 2024-11-01 at 2 14 51 AM](https://github.com/user-attachments/assets/09c7861d-9840-4595-9ea3-cd2a4eed3374)

### Suggested improvement
- Make these commands case insensitive (might be preferable for sake of consistency)
- Or update the user guide to specify that they aren't

**Comment by LynetteLeeSiYing** [comment]
I think it is already mentioned that the 'find' command would be case insensitive in the user guide

**Screenshots**
<img width="400" alt="image" src="https://github.com/user-attachments/assets/863633ab-103a-467d-bd28-c00f5f4489d1">
