### ISSUE TITLE
Find Command: Update the Error Message

### ISSUE THREAD

**Issue by ritvi12** [AY2425S1-CS2103T-T10-1/tp#139]
### Description

Currently on having a blank field in find results in the description of the command to be given as error 

<img width="1350" alt="Screenshot 2024-11-01 at 2 19 49 PM" src="https://github.com/user-attachments/assets/c9a0c23d-7e52-4e63-b820-0f84c24e5685">

### Suggested Improvement

Make the error message more precise so that the user is clear on what the error is.

**Comment by LynetteLeeSiYing** [comment]
I was actually doing this intentionally to let users know the right format of it, similar to the other command, e.g. DELETE, when there is no other parameters, the message usage will be shown.
