### ISSUE TITLE
View Command: Update view note behaviour

### ISSUE THREAD

**Issue by ritvi12** [AY2425S1-CS2103T-T10-1/tp#142]
### Description

At first the command shows this output but on clicking the name the note part disappears
<img width="1344" alt="Screenshot 2024-11-01 at 2 33 26 PM" src="https://github.com/user-attachments/assets/c45d6bea-f2b7-45f1-8b72-ccdab3f26550">

<img width="1203" alt="Screenshot 2024-11-01 at 2 34 22 PM" src="https://github.com/user-attachments/assets/ac6cb908-e3ed-4ac5-b8ee-c26a45515f62">

### Suggested Improvement

The note should not disapper

**Comment by myrilla12** [comment]
I think this bug has already been brought up in issue #128

**Comment by myrilla12** [comment]
To add to this, the same situation occurs if the user has clicked on the contact before typing View, the note does not appear. 
![Screenshot 2024-11-01 at 11 28 35 PM](https://github.com/user-attachments/assets/30470253-685e-4ba5-b646-df3818fb37e5)

I think Kelly's suggestion in issue #128 would be the easiest to fix this (remove the clicking contact function overall)
