### ISSUE TITLE
Delete command: inconsistent error message 

### ISSUE THREAD

**Issue by LynetteLeeSiYing** [AY2425S1-CS2103T-T10-1/tp#143]
**Description**
Inconsistent error message on deleting invalid names and deleting invalid index. 

**Screenshots**
<img width="729" alt="Screenshot 2024-11-01 at 2 22 48 PM" src="https://github.com/user-attachments/assets/0d1aa87b-85e5-4318-9003-dcb9ca6fc197">
<img width="724" alt="Screenshot 2024-11-01 at 2 29 00 PM" src="https://github.com/user-attachments/assets/3da0425f-6f34-4b6e-b84a-f730be3dce93">

**Comment by ritvi12** [comment]
I am bit confused as to what is the bug? Like depending on the input it throws a specific error message right. Is there any particular improvement or change that is needed?

**Comment by LynetteLeeSiYing** [comment]
> I am bit confused as to what is the bug? Like depending on the input it throws a specific error message right. Is there any particular improvement or change that is needed?

Just a minor issue: the grammar on both error message are inconsistent, i.e. person / person's ? maybe can follow the other error commands practice
