### ISSUE TITLE
Edit & Note Command: Previous and future appointment dates falsely permitted

### ISSUE THREAD

**Issue by myrilla12** [AY2425S1-CS2103T-T10-1/tp#154]
### Description
Person can have an appointment that is set in the past in the appointments section and appointments set in the future in notes-appointments section. 
![Screenshot 2024-11-01 at 11 14 29 PM](https://github.com/user-attachments/assets/5ab9e75f-5568-4ed2-8a68-0a9b1c98bf0f)

My understanding was that appointments would just display incoming appointments while the notes-appointments section would contain previous appointments. Maybe I understood wrong and this is just a potential extension. But the fact that notes calls it 'Previous Appointments' in the UI would make this a bug. 

### Suggested improvements
- Can implement that but then might also need to consider appointments automatically moving from appointments to notes upon the dates passing. 
- Otherwise can just clarify appointment constraints in UG and modify the `Previous Appointments` to just say `Appointments`

**Comment by OttoTan** [comment]
Automatic movement of appointments is already been implemented. Will introduce the new constraint.
