### ISSUE TITLE
[PE-D][Tester B] Delete command opens a popup window, which goes against CLI constraints of the TP

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-1/tp#195]
**Steps to Reproduce**:
1. Enter `delete 7` into command line.

**Expected Result**:  
All interactions should be constrained within the CLI, per project requirements.

**Actual Result**:  
A popup window is generated, which contradicts the requirement for a CLI-based tool.

![Screenshot 2024-11-08 at 16.28.23.png](https://raw.githubusercontent.com/TechRaj/ped/main/files/d501ca82-2eaa-4c26-9127-55e6739876e6.png)

**Proposed Solution**:  
- Implement an in-CLI solution to replace the popup window.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: TechRaj/ped#3

**Comment by Bonzzz3** [comment]
It is stated in UG that there are keyboard shortcuts to trigger the confirmation process so it supports CLI. Additionally, it only requires user to click once. Clicking buttons to exit app, to see help window, to enter command also require 1 or more clicks. I don't think this is a valid bug report as it does not violate project requirements.

![image](https://github.com/user-attachments/assets/9f44e01d-6bfc-421c-a006-cc20904496ff)
