### ISSUE TITLE
[PE-D][Tester A] Phone numbers should not be only limited to 8 digits

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-1/tp#216]
There is no mention of the specificity of country or region in the user guide, which means that more regions should be considered when accepting phone numbers. Therefore, limiting phone numbers to exclusively 8 digits excludes people from many other foreign countries.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Green-Tea-123/ped#5

**Comment by myrilla12** [comment]
Updated the UG to include the target audience.
