### ISSUE TITLE
[PE-D][Tester C] Invalid dates are allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-1/tp#224]
Steps to Reproduce:
1. Add any appointment with date 31 on a month with less than 31 days.
e.g.
`edit Alex Yeoh ap/31/02/2025 0000`

Expected:
Error Message: invalid date

Actual:
Date is "rounded down" to nearest valid date and accepted.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: engyuhan/ped#4

**Comment by myrilla12** [comment]
Duplicated issue.
