### ISSUE TITLE
[PE-D][Tester B] Unclear acknowledgements in Developer Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-1/tp#237]
**Steps to Reproduce**:
1. Open the Developer Guide (DG) for MediContact.
2. Check the acknowledgements section.

**Expected Result**:  
Clear and specific acknowledgements of contributions.

**Actual Result**:  
Acknowledgements are unclear and ambiguous.

![Screenshot 2024-11-08 at 18.18.12.png](https://raw.githubusercontent.com/TechRaj/ped/main/files/78c2f56b-dcb1-4b35-9a16-3a2e485b2be3.png)

**Proposed Solution**:  
- Update the acknowledgements to clearly list all contributors.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: TechRaj/ped#14

**Comment by myrilla12** [comment]
Fine we will list contributors.
