### ISSUE TITLE
[PE-D][Tester E] Incorrect links provided in the DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-1/tp#251]
Some links under Design lead to the AddressBook-3 Repository instead of your own; which might cause some information to be outdated.

Example is Main and MainApp here:

![image.png](https://raw.githubusercontent.com/ulricolo7/ped/main/files/211799c1-8637-4e5e-8f93-dd2a49b95ee2.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ulricolo7/ped#14

**Comment by myrilla12** [comment]
ok
