### ISSUE TITLE
[PE-D][Tester A] star not working for names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-1/tp#257]
![image.png](https://raw.githubusercontent.com/Green-Tea-123/ped/main/files/3f91bd83-275a-4ffc-b0e9-42a42cf0efcd.png)
I tried starring a person and got a completely different error message. The user guide even specifies that the operation exists.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Green-Tea-123/ped#8

**Comment by myrilla12** [comment]
Same bug present for `delete` and `unstar`

**Comment by myrilla12** [comment]
Solution to be implemented: Restrict names to only accept alphabets (rmb to update UG parameter constraints)
